--------------------------------------------------------
--  File created - czwartek-listopada-27-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EXAMPLE_USERS
--------------------------------------------------------

  CREATE TABLE "EXAMPLE_USERS" 
   (	"ID" NUMBER(*,0), 
	"LOGIN" VARCHAR2(30), 
	"IMIE" VARCHAR2(30), 
	"NAZWISKO" VARCHAR2(30), 
	"DEPARTMENT_ID" NUMBER, 
	"STATUS" VARCHAR2(20)
   ) ;
REM INSERTING into EXAMPLE_USERS
SET DEFINE OFF;
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('22','djanik','Daniel','Janik','7','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('42','pmarcz','Piotr','Marczak ','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('43','dchmie','Damian','Chmiel ','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('44','apiąte','Arkadiusz','Piątek','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('63','jsawic','Julia','Sawicka','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('62','iwróbl','Iwona','Wróblewska','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('21','isikor','Izabela','Sikorska ','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('82','kkubic','Krystian','Kubicki','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('222','kmicha','Kinga','Michalak ','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('243','askiba','Artur','Skiba','10','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('244','mbaran','Mateusz','Baranowski','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('376','emałec','Elżbieta','Małecka','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('377','wpająk','Weronika','Pająk','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('378','lkazim','Leszek','Kazimierczak','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('379','mchrza','Monika','Chrzanowska','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('380','jmicha','Justyna','Michalska','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('381','pżukow','Patrycja','Żukowska','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('382','awoźni','Agata','Woźniak','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('383','dkołod','Dariusz','Kołodziejczyk ','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('384','kmarci','Kamila','Marciniak','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('386','kwitko','Kinga','Witkowska','6','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('387','tbrzez','Tomasz','Brzeziński','4','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('388','mwójci','Marta','Wójcik','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('389','tmajew','Tomasz','Majewski','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('390','rpolak','Ryszard','Polak','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('391','mskowr','Mariusz','Skowroński','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('392','djanko','Dariusz','Jankowski','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('393','jwesoł','Janusz','Wesołowski','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('395','zchmie','Zbigniew','Chmiel ','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('397','mmicha','Magdalena','Michalska','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('398','ujabło','Urszula','Jabłońska','3','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('399','mgrzyb','Marta','Grzybowska','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('400','zjasiń','Zbigniew','Jasiński','10','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('401','idudek','Iwona','Dudek','7','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('402','awiecz','Arkadiusz','Wieczorek','6','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('403','mkaźmi','Mariusz','Kaźmierczak','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('404','kkałuż','Krystian','Kałuża ','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('406','mdąbro','Marek','Dąbrowski','5','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('407','iadamc','Igor','Adamczak','3','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('142','mkurow','Monika','Kurowska','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('182','pchmie','Paulina','Chmielewska','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('282','kkowal','Kacper','Kowalski','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('283','wmikoł','Wioletta','Mikołajczyk','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('284','aborow','Adrian','Borowski','6','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('285','kcieśl','Kamil','Cieślik ','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('287','mmróz','Mirosław','Mróz','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('288','ajabło','Adam','Jabłoński','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('289','aurbań','Artur','Urbański','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('290','mbrzez','Marek','Brzeziński','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('291','mczarn','Michał','Czarnecki','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('292','mwiśni','Marzena','Wiśniewska','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('293','eziółk','Edyta','Ziółkowska','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('294','awróbe','Agata','Wróbel','6','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('296','sczajk','Sebastian','Czajka','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('297','awójci','Aleksandra','Wójcik','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('298','iszulc','Ireneusz','Szulc','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('299','wczarn','Wioletta','Czarnecka','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('300','pmróz','Patryk','Mróz','2','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('301','dkrupa','Dorota','Krupa','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('302','abaran','Arkadiusz','Baranowski','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('303','dpawli','Daniel','Pawlik','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('304','spawło','Sebastian','Pawłowski','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('305','kzakrz','Kamila','Zakrzewska','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('307','wzalew','Weronika','Zalewska','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('309','jleśni','Jakub','Leśniak','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('310','mmacie','Michał','Maciejewski','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('311','pwalcz','Paulina','Walczak','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('312','gandrz','Grzegorz','Andrzejewski','4','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('102','jrożek','Jan','Rożek','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('103','rgórsk','Robert','Górski','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('122','eszcze','Elżbieta','Szczepańska ','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('314','mpająk','Marta','Pająk','9','zablokowany');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('316','lgajew','Leszek','Gajewski','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('317','imarci','Irena','Marciniak','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('318','akozło','Andrzej','Kozłowski','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('319','rmikoł','Renata','Mikołajczyk','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('321','jkołod','Janusz','Kołodziejczyk ','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('322','epająk','Elżbieta','Pająk','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('324','dkrawc','Dominika','Krawczyk','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('326','kmikoł','Krzysztof','Mikołajczak','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('328','apawla','Aleksandra','Pawlak ','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('329','asikor','Anna Maria','Sikora','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('330','sżukow','Sebastian','Żukowski','3','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('332','ksobol','Krystian','Sobolewski ','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('333','achrza','Anna Maria','Chrzanowska','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('334','emikoł','Emilia','Mikołajczyk','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('336','tjanow','Tadeusz','Janowski ','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('338','jurban','Julia','Urbaniak','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('340','mczerw','Maria','Czerwińska','5','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('341','pjabło','Patryk','Jabłoński','5','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('342','pmrozo','Patryk','Mrozowski ','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('343','istola','Ireneusz','Stolarczyk ','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('344','gmicha','Gabriela','Michalak ','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('345','ikrzes','Igor','Krzesiński','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('348','ljanik','Leszek','Janik','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('350','rpawło','Robert','Pawłowski','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('352','hwiśni','Henryk','Wiśniewski','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('353','pjanik','Piotr','Janik','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('356','mmazur','Marta','Mazur','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('357','dwesoł','Dorota','Wesołowska','5','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('359','lstola','Leszek','Stolarczyk ','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('361','slis','Szymon','Lis','2','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('363','gpawla','Grażyna','Pawlak ','1','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('364','kkaczm','Karolina','Kaczmarczyk','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('366','pskals','Patryk','Skalski','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('367','amazur','Adam','Mazurek','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('368','awrona','Adam','Wrona ','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('370','bsosno','Bartosz','Sosnowski','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('371','gwesoł','Grzegorz','Wesołowski','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('372','knowak','Krzysztof','Nowakowski','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('375','rjasiń','Ryszard','Jasiński','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('642','rjanko','Renata','Jankowska','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('409','rolsze','Ryszard','Olszewski','4','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('412','mborow','Mateusz','Borowski','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('413','mkowal','Marzena','Kowalczyk','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('414','mzalew','Marta','Zalewska','9','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('417','agrabo','Artur','Grabowski','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('419','msikor','Marzena','Sikorska ','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('421','rkowal','Renata','Kowalczyk','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('423','mstępi','Mateusz','Stępień','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('424','akrzes','Arkadiusz','Krzesiński','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('427','mszymc','Marek','Szymczak ','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('430','twesoł','Tadeusz','Wesołowski','4','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('431','durban','Dominika','Urbaniak','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('434','aszyma','Anna Maria','Szymańska','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('435','pzalew','Patryk','Zalewski','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('436','tzalew','Tomasz','Zalewski','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('438','pbąkow','Patryk','Bąkowski','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('439','jzieli','Joanna','Zielińska','9','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('441','njanko','Norbert','Jankowski','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('443','gmalin','Grzegorz','Malinowski','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('444','dadamc','Dariusz','Adamczak','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('447','tgłowa','Tomasz','Głowacki','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('448','mjastr','Maria','Jastrzębska ','3','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('450','wwrona','Waldemar','Wrona ','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('451','bgórec','Barbara','Górecka','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('452','emakow','Ewelina','Makowska','2','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('454','jszulc','Jacek','Szulc','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('455','pwoźni','Patrycja','Woźniak','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('458','ewalcz','Edyta','Walczak','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('461','cskowr','Cezary','Skowroński','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('462','awiśni','Adrian','Wiśniewski','4','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('463','kmazur','Kinga','Mazur','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('465','rtomcz','Robert','Tomczak','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('466','jjaros','Jacek','Jarosz','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('467','jsobcz','Justyna','Sobczak','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('468','łpiotr','Łukasz','Piotrowski','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('470','kmacie','Karolina','Maciejewska','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('471','ajanko','Agnieszka','Jankowska','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('472','mwesoł','Marta','Wesołowska','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('473','kstank','Kinga','Stankiewicz','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('474','emazur','Elżbieta','Mazur','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('476','pkaczm','Paulina','Kaczmarek','1','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('477','agłowa','Anita','Głowacka','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('479','nbaran','Natalia','Baran','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('480','wświde','Wojciech','Świderski ','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('481','arosiń','Anna Maria','Rosińska','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('482','mmakow','Marta','Makowska','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('483','wsobcz','Weronika','Sobczak','5','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('484','kwłoda','Kamila','Włodarczyk ','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('485','ppasie','Paulina','Pasieka','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('486','mleszc','Mateusz','Leszczyński','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('487','mrogow','Mariusz','Rogowski','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('489','dzalew','Daniel','Zalewski','3','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('490','mjaros','Marek','Jarosz','3','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('492','kszyma','Karolina','Szymańska','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('493','rświde','Rafał','Świderski ','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('494','mwrona','Mirosław','Wrona ','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('495','agrzyb','Agnieszka','Grzybowska','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('496','ppolak','Piotr','Polak','7','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('497','kszewc','Kamila','Szewczyk','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('498','iwłoda','Igor','Włodarczyk','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('499','rtarno','Radosław','Tarnowski','4','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('500','jstola','Jacek','Stolarczyk ','1','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('501','kpasie','Karolina','Pasieka','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('502','tnowic','Teresa','Nowicka','5','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('503','rkrzes','Ryszard','Krzesiński','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('504','dkałuż','Dariusz','Kałuża ','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('505','gmrozo','Grzegorz','Mrozowski ','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('506','dborow','Dariusz','Borowicz ','1','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('508','mżukow','Marek','Żukowski','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('509','ikrawc','Ireneusz','Krawczak','5','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('510','nchmie','Norbert','Chmiel ','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('512','ssobol','Sylwia','Sobolewska','4','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('514','jkrzes','Jarosław','Krzesiński','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('515','gmarci','Gabriela','Marciniak','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('516','polsze','Paweł','Olszewski','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('517','kmakow','Kazimierz','Makowski','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('519','hjanik','Henryk','Janik','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('521','jkrupa','Julia','Krupa','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('522','ljasiń','Leszek','Jasiński','7','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('523','ezawad','Emilia','Zawadzka','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('524','itomcz','Igor','Tomczak','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('525','iczerw','Iwona','Czerwińska','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('526','kwojci','Karolina','Wojciechowska','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('527','pdudek','Patrycja','Dudek','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('528','apasie','Anna Maria','Pasieka','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('529','rbaran','Ryszard','Baranowski','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('530','jłucza','Julia','Łuczak','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('531','mkubic','Marzena','Kubicka','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('532','isosno','Ireneusz','Sosnowski','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('533','dgłowa','Damian','Głowacki','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('534','jbrzez','Jacek','Brzeziński','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('535','jmalin','Janusz','Malinowski','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('537','izawad','Izabela','Zawadzka','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('538','kwesoł','Katarzyna','Wesołowska','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('542','ssikor','Sylwia','Sikora','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('543','mmikoł','Marzena','Mikołajczyk','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('544','mmadej','Marzena','Madej','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('546','zskiba','Zbigniew','Skiba','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('547','mskals','Mariusz','Skalski','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('548','jurbań','Jarosław','Urbański','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('549','awłoda','Anna Maria','Włodarczyk ','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('550','uwilk','Urszula','Wilk','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('551','epiotr','Ewelina','Piotrowska','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('552','akwiat','Agnieszka','Kwiatkowska','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('554','awalcz','Anita','Walczak','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('555','abedna','Aleksandra','Bednarska','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('556','jzakrz','Jakub','Zakrzewski','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('557','jwiśni','Janusz','Wiśniewski','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('558','jzawad','Julia','Zawadzka','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('560','mduda','Monika','Duda','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('564','hcieśl','Henryk','Cieślak','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('565','ekozak','Elżbieta','Kozak','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('566','dstępi','Daniel','Stępień','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('567','aczarn','Aleksandra','Czarnecka','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('569','krogow','Kacper','Rogowski','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('570','anowak','Agata','Nowak','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('573','dszymc','Daniel','Szymczak ','10','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('574','mmalin','Mariusz','Malinowski','7','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('575','mwróbe','Maria','Wróbel','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('577','akaczm','Aleksandra','Kaczmarczyk','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('578','mkról','Małgorzata','Król','7','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('579','amikoł','Agnieszka','Mikołajczyk','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('583','dzawad','Dorota','Zawadzka','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('584','iwitko','Irena','Witkowska','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('585','łkwiat','Łukasz','Kwiatkowski','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('586','zgórsk','Zbigniew','Górski','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('587','kmalin','Katarzyna','Malinowska','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('588','mkrawc','Małgorzata','Krawczyk','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('590','jzając','Joanna','Zając','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('591','jkubic','Jan','Kubicki','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('592','aolsze','Alicja','Olszewska','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('593','mzając','Monika','Zając','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('596','ilewan','Ireneusz','Lewandowski','4','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('597','wżukow','Waldemar','Żukowski','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('599','gkrzes','Grzegorz','Krzesiński','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('600','bgłowa','Beata','Głowacka','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('601','kkraje','Klaudia','Krajewska ','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('602','molsze','Monika','Olszewska','6','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('603','kłukas','Katarzyna','Łukasik','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('604','mcieśl','Michał','Cieślik ','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('605','aszulc','Adam','Szulc','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('606','apasze','Andrzej','Paszek','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('610','atomas','Agata','Tomaszewska','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('611','skania','Sebastian','Kania','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('613','mświde','Marek','Świderski ','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('614','akrupa','Anna','Krupa','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('615','csikor','Cezary','Sikorski','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('617','msobol','Magdalena','Sobolewska','6','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('618','wmarci','Wioletta','Marciniak','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('619','jpasze','Janusz','Paszek','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('620','rleśni','Radosław','Leśniak','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('623','dolsze','Dariusz','Olszewski','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('662','jszewc','Justyna','Szewczyk','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('682','ałucza','Agata','Łuczak','9','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('745','pmakow','Patrycja','Makowska','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('746','ujasiń','Urszula','Jasińska','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('747','jborko','Jakub','Borkowski ','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('749','rjóźwi','Robert','Jóźwiak ','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('750','jrogow','Jan','Rogowski','8','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('782','rcieśl','Radosław','Cieślak','3','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('784','ltarno','Leszek','Tarnowski','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('785','pwojci','Paulina','Wojciechowska','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('822','jtomcz','Jarosław','Tomczak','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('847','eszyma','Ewa','Szymańska','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('846','bmikoł','Bartłomiej','Mikołajczak','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('848','iwiśni','Irena','Wiśniewska','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('850','swilk','Sylwia','Wilk','9','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('308','akraje','Alicja','Krajewska ','10','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('313','agórec','Agnieszka','Górecka','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('162','mtomcz','Marcin','Tomczak','6','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('315','hstola','Henryk','Stolarczyk ','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('320','jpolak','Jarosław','Polak','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('323','ibedna','Igor','Bednarski','2','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('327','alewan','Alicja','Lewandowska','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('331','jleszc','Jakub','Leszczyński','8','zablokowany');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('335','adąbro','Anita','Dąbrowska','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('339','mmajew','Mirosław','Majewski','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('202','wwawrz','Weronika','Wawrzyniak','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('346','mjasiń','Magdalena','Jasińska','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('351','twróbl','Tadeusz','Wróblewski','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('355','akowal','Anna','Kowalska','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('358','wurban','Weronika','Urbaniak','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('362','ibaran','Izabela','Baran','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('365','amicha','Adam','Michalski','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('369','kbaran','Klaudia','Baran','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('373','gjaros','Grzegorz','Jarosz','5','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('783','aszymc','Artur','Szymczak ','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('411','mpawło','Michał','Pawłowski','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('418','kpiotr','Kamil','Piotrowski','6','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('422','igórsk','Izabela','Górska','10','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('426','jjasiń','Jakub','Jasiński','2','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('429','ikaspr','Irena','Kasprzak','1','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('433','mgajew','Maria','Gajewska','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('440','dczarn','Damian','Czarnecki','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('445','kjanow','Krzysztof','Janowski ','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('449','kszcze','Karolina','Szczepańska ','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('453','mpolak','Marcin','Polak','8','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('457','jwrona','Jacek','Wrona ','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('460','pleśni','Piotr','Leśniak','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('464','jtarno','Janusz','Tarnowski','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('408','mkołod','Marcin','Kołodziejczyk ','3','zablokowany');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('245','jsikor','Jolanta','Sikora','8','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('385','ipiotr','Ireneusz','Piotrowski','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('396','ksobcz','Krystyna','Sobczak','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('405','kgórsk','Krystyna','Górska','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('286','jpawli','Jacek','Pawlik','6','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('306','kjaros','Krzysztof','Jarosz','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('262','igajew','Irena','Gajewska','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('325','jkwiat','Jan','Kwiatkowski','7','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('337','ljanow','Leszek','Janowski ','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('349','spasie','Sylwia','Pasieka','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('360','kczajk','Karolina','Czajkowska','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('374','eczajk','Emilia','Czajkowska','5','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('420','gpiase','Grzegorz','Piasecki','9','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('432','jkaźmi','Jacek','Kaźmierczak','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('446','rparty','Robert','Partyka','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('456','dmrozo','Daniel','Mrozowski ','2','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('536','wpawli','Waldemar','Pawlik','7','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('545','atomcz','Adam','Tomczak','4','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('553','pkozak','Paulina','Kozak','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('562','jkubia','Jarosław','Kubiak','3','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('571','dgrzyb','Dominika','Grzybowska','1','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('581','tpolak','Tadeusz','Polak','5','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('589','ipiąte','Igor','Piątek','8','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('616','wkwiat','Waldemar','Kwiatkowski','10','aktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('702','dleśni','Damian','Leśniak','4','nieaktywny');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID,STATUS) values ('803','jbedna','Janusz','Bednarski','5','aktywny');
--------------------------------------------------------
--  DDL for Index SYS_C0048732463
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0048732463" ON "EXAMPLE_USERS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index UQ_EXAMPLE_USERS_LOGIN
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_EXAMPLE_USERS_LOGIN" ON "EXAMPLE_USERS" ("LOGIN") 
  ;
--------------------------------------------------------
--  Constraints for Table EXAMPLE_USERS
--------------------------------------------------------

  ALTER TABLE "EXAMPLE_USERS" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "EXAMPLE_USERS" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "EXAMPLE_USERS" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "EXAMPLE_USERS" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "EXAMPLE_USERS" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "EXAMPLE_USERS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "EXAMPLE_USERS" ADD CONSTRAINT "UQ_EXAMPLE_USERS_LOGIN" UNIQUE ("LOGIN")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXAMPLE_USERS
--------------------------------------------------------

  ALTER TABLE "EXAMPLE_USERS" ADD CONSTRAINT "FK_USERS_EXAMPLE_DEPT" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "EXAMPLE_DEPARTMENTS" ("ID") ENABLE;
