--------------------------------------------------------
--  File created - niedziela-listopada-23-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EXAMPLE_USERS
--------------------------------------------------------

  CREATE TABLE "EXAMPLE_USERS" 
   (	"ID" NUMBER(10,1), 
	"LOGIN" VARCHAR2(30), 
	"IMIE" VARCHAR2(30), 
	"NAZWISKO" VARCHAR2(30), 
	"DEPARTMENT_ID" NUMBER
   ) ;
REM INSERTING into EXAMPLE_USERS
SET DEFINE OFF;
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('22','djanik','Daniel','Janik','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('42','pmarcz','Piotr','Marczak ','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('43','dchmie','Damian','Chmiel ','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('44','apiąte','Arkadiusz','Piątek','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('63','jsawic','Julia','Sawicka','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('62','iwróbl','Iwona','Wróblewska','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('21','isikor','Izabela','Sikorska ','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('82','kkubic','Krystian','Kubicki','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('222','kmicha','Kinga','Michalak ','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('243','askiba','Artur','Skiba','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('244','mbaran','Mateusz','Baranowski','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('245','jsikor','Jolanta','Sikora','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('376','emałec','Elżbieta','Małecka','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('377','wpająk','Weronika','Pająk','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('378','lkazim','Leszek','Kazimierczak','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('379','mchrza','Monika','Chrzanowska','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('380','jmicha','Justyna','Michalska','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('381','pżukow','Patrycja','Żukowska','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('382','awoźni','Agata','Woźniak','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('383','dkołod','Dariusz','Kołodziejczyk ','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('384','kmarci','Kamila','Marciniak','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('385','ipiotr','Ireneusz','Piotrowski','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('386','kwitko','Kinga','Witkowska','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('387','tbrzez','Tomasz','Brzeziński','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('388','mwójci','Marta','Wójcik','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('389','tmajew','Tomasz','Majewski','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('390','rpolak','Ryszard','Polak','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('391','mskowr','Mariusz','Skowroński','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('392','djanko','Dariusz','Jankowski','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('393','jwesoł','Janusz','Wesołowski','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('395','zchmie','Zbigniew','Chmiel ','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('396','ksobcz','Krystyna','Sobczak','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('397','mmicha','Magdalena','Michalska','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('398','ujabło','Urszula','Jabłońska','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('399','mgrzyb','Marta','Grzybowska','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('400','zjasiń','Zbigniew','Jasiński','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('401','idudek','Iwona','Dudek','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('402','awiecz','Arkadiusz','Wieczorek','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('403','mkaźmi','Mariusz','Kaźmierczak','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('404','kkałuż','Krystian','Kałuża ','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('405','kgórsk','Krystyna','Górska','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('406','mdąbro','Marek','Dąbrowski','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('407','iadamc','Igor','Adamczak','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('408','mkołod','Marcin','Kołodziejczyk ','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('142','mkurow','Monika','Kurowska','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('182','pchmie','Paulina','Chmielewska','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('282','kkowal','Kacper','Kowalski','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('283','wmikoł','Wioletta','Mikołajczyk','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('284','aborow','Adrian','Borowski','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('285','kcieśl','Kamil','Cieślik ','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('286','jpawli','Jacek','Pawlik','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('287','mmróz','Mirosław','Mróz','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('288','ajabło','Adam','Jabłoński','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('289','aurbań','Artur','Urbański','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('290','mbrzez','Marek','Brzeziński','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('291','mczarn','Michał','Czarnecki','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('292','mwiśni','Marzena','Wiśniewska','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('293','eziółk','Edyta','Ziółkowska','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('294','awróbe','Agata','Wróbel','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('295','wwawrz','Weronika','Wawrzyniak','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('296','sczajk','Sebastian','Czajka','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('297','awójci','Aleksandra','Wójcik','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('298','iszulc','Ireneusz','Szulc','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('299','wczarn','Wioletta','Czarnecka','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('300','pmróz','Patryk','Mróz','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('301','dkrupa','Dorota','Krupa','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('302','abaran','Arkadiusz','Baranowski','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('303','dpawli','Daniel','Pawlik','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('304','spawło','Sebastian','Pawłowski','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('305','kzakrz','Kamila','Zakrzewska','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('306','kjaros','Krzysztof','Jarosz','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('307','wzalew','Weronika','Zalewska','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('308','akraje','Alicja','Krajewska ','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('309','jleśni','Jakub','Leśniak','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('310','mmacie','Michał','Maciejewski','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('311','pwalcz','Paulina','Walczak','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('312','gandrz','Grzegorz','Andrzejewski','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('313','agórec','Agnieszka','Górecka','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('102','jrożek','Jan','Rożek','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('103','rgórsk','Robert','Górski','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('122','eszcze','Elżbieta','Szczepańska ','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('162','mtomcz','Marcin','Tomczak','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('262','igajew','Irena','Gajewska','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('314','mpająk','Marta','Pająk','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('315','hstola','Henryk','Stolarczyk ','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('316','lgajew','Leszek','Gajewski','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('317','imarci','Irena','Marciniak','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('318','akozło','Andrzej','Kozłowski','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('319','rmikoł','Renata','Mikołajczyk','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('320','jpolak','Jarosław','Polak','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('321','jkołod','Janusz','Kołodziejczyk ','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('322','epająk','Elżbieta','Pająk','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('323','ibedna','Igor','Bednarski','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('324','dkrawc','Dominika','Krawczyk','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('325','jkwiat','Jan','Kwiatkowski','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('326','kmikoł','Krzysztof','Mikołajczak','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('327','alewan','Alicja','Lewandowska','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('328','apawla','Aleksandra','Pawlak ','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('329','asikor','Anna Maria','Sikora','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('330','sżukow','Sebastian','Żukowski','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('331','jleszc','Jakub','Leszczyński','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('332','ksobol','Krystian','Sobolewski ','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('333','achrza','Anna Maria','Chrzanowska','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('334','emikoł','Emilia','Mikołajczyk','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('335','adąbro','Anita','Dąbrowska','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('336','tjanow','Tadeusz','Janowski ','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('337','ljanow','Leszek','Janowski ','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('338','jurban','Julia','Urbaniak','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('339','mmajew','Mirosław','Majewski','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('340','mczerw','Maria','Czerwińska','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('341','pjabło','Patryk','Jabłoński','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('342','pmrozo','Patryk','Mrozowski ','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('202','wwawrz','Weronika','Wawrzyniak','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('343','istola','Ireneusz','Stolarczyk ','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('344','gmicha','Gabriela','Michalak ','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('345','ikrzes','Igor','Krzesiński','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('346','mjasiń','Magdalena','Jasińska','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('347','jleszc','Jacek','Leszczyński','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('348','ljanik','Leszek','Janik','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('349','spasie','Sylwia','Pasieka','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('350','rpawło','Robert','Pawłowski','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('351','twróbl','Tadeusz','Wróblewski','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('352','hwiśni','Henryk','Wiśniewski','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('353','pjanik','Piotr','Janik','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('354','mwiśni','Małgorzata','Wiśniewska','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('355','akowal','Anna','Kowalska','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('356','mmazur','Marta','Mazur','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('357','dwesoł','Dorota','Wesołowska','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('358','wurban','Weronika','Urbaniak','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('359','lstola','Leszek','Stolarczyk ','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('360','kczajk','Karolina','Czajkowska','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('361','slis','Szymon','Lis','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('362','ibaran','Izabela','Baran','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('363','gpawla','Grażyna','Pawlak ','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('364','kkaczm','Karolina','Kaczmarczyk','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('365','amicha','Adam','Michalski','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('366','pskals','Patryk','Skalski','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('367','amazur','Adam','Mazurek','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('368','awrona','Adam','Wrona ','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('369','kbaran','Klaudia','Baran','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('370','bsosno','Bartosz','Sosnowski','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('371','gwesoł','Grzegorz','Wesołowski','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('372','knowak','Krzysztof','Nowakowski','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('373','gjaros','Grzegorz','Jarosz','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('374','eczajk','Emilia','Czajkowska','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('375','rjasiń','Ryszard','Jasiński','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('642','rjanko','Renata','Jankowska','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('783','aszymc','Artur','Szymczak ','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('409','rolsze','Ryszard','Olszewski','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('410','imarci','Irena','Marciniak','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('411','mpawło','Michał','Pawłowski','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('412','mborow','Mateusz','Borowski','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('413','mkowal','Marzena','Kowalczyk','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('414','mzalew','Marta','Zalewska','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('415','mbaran','Maria','Baran','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('416','rolsze','Radosław','Olszewski','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('417','agrabo','Artur','Grabowski','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('418','kpiotr','Kamil','Piotrowski','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('419','msikor','Marzena','Sikorska ','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('420','gpiase','Grzegorz','Piasecki','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('421','rkowal','Renata','Kowalczyk','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('422','igórsk','Izabela','Górska','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('423','mstępi','Mateusz','Stępień','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('424','akrzes','Arkadiusz','Krzesiński','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('425','lgajew','Leszek','Gajewski','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('426','jjasiń','Jakub','Jasiński','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('427','mszymc','Marek','Szymczak ','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('428','mkołod','Mateusz','Kołodziej','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('429','ikaspr','Irena','Kasprzak','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('430','twesoł','Tadeusz','Wesołowski','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('431','durban','Dominika','Urbaniak','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('432','jkaźmi','Jacek','Kaźmierczak','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('433','mgajew','Maria','Gajewska','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('434','aszyma','Anna Maria','Szymańska','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('435','pzalew','Patryk','Zalewski','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('436','tzalew','Tomasz','Zalewski','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('437','pmrozo','Paweł','Mrozowski ','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('438','pbąkow','Patryk','Bąkowski','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('439','jzieli','Joanna','Zielińska','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('440','dczarn','Damian','Czarnecki','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('441','njanko','Norbert','Jankowski','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('442','mmicha','Mateusz','Michalski','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('443','gmalin','Grzegorz','Malinowski','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('444','dadamc','Dariusz','Adamczak','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('445','kjanow','Krzysztof','Janowski ','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('446','rparty','Robert','Partyka','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('447','tgłowa','Tomasz','Głowacki','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('448','mjastr','Maria','Jastrzębska ','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('449','kszcze','Karolina','Szczepańska ','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('450','wwrona','Waldemar','Wrona ','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('451','bgórec','Barbara','Górecka','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('452','emakow','Ewelina','Makowska','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('453','mpolak','Marcin','Polak','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('454','jszulc','Jacek','Szulc','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('455','pwoźni','Patrycja','Woźniak','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('456','dmrozo','Daniel','Mrozowski ','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('457','jwrona','Jacek','Wrona ','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('458','ewalcz','Edyta','Walczak','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('459','mbrzez','Marek','Brzeziński','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('460','pleśni','Piotr','Leśniak','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('461','cskowr','Cezary','Skowroński','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('462','awiśni','Adrian','Wiśniewski','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('463','kmazur','Kinga','Mazur','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('464','jtarno','Janusz','Tarnowski','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('465','rtomcz','Robert','Tomczak','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('466','jjaros','Jacek','Jarosz','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('467','jsobcz','Justyna','Sobczak','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('468','łpiotr','Łukasz','Piotrowski','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('469','jzieli','Jolanta','Zielińska','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('470','kmacie','Karolina','Maciejewska','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('471','ajanko','Agnieszka','Jankowska','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('472','mwesoł','Marta','Wesołowska','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('473','kstank','Kinga','Stankiewicz','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('474','emazur','Elżbieta','Mazur','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('475','kzakrz','Krzysztof','Zakrzewski','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('476','pkaczm','Paulina','Kaczmarek','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('477','agłowa','Anita','Głowacka','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('478','aszyma','Agnieszka','Szymańska','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('479','nbaran','Natalia','Baran','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('480','wświde','Wojciech','Świderski ','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('481','arosiń','Anna Maria','Rosińska','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('482','mmakow','Marta','Makowska','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('483','wsobcz','Weronika','Sobczak','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('484','kwłoda','Kamila','Włodarczyk ','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('485','ppasie','Paulina','Pasieka','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('486','mleszc','Mateusz','Leszczyński','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('487','mrogow','Mariusz','Rogowski','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('488','kkaczm','Krystyna','Kaczmarek','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('489','dzalew','Daniel','Zalewski','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('490','mjaros','Marek','Jarosz','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('491','kpiotr','Katarzyna','Piotrowska','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('492','kszyma','Karolina','Szymańska','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('493','rświde','Rafał','Świderski ','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('494','mwrona','Mirosław','Wrona ','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('495','agrzyb','Agnieszka','Grzybowska','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('496','ppolak','Piotr','Polak','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('497','kszewc','Kamila','Szewczyk','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('498','iwłoda','Igor','Włodarczyk','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('499','rtarno','Radosław','Tarnowski','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('500','jstola','Jacek','Stolarczyk ','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('501','kpasie','Karolina','Pasieka','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('502','tnowic','Teresa','Nowicka','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('503','rkrzes','Ryszard','Krzesiński','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('504','dkałuż','Dariusz','Kałuża ','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('505','gmrozo','Grzegorz','Mrozowski ','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('506','dborow','Dariusz','Borowicz ','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('507','kcieśl','Krystian','Cieślik ','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('508','mżukow','Marek','Żukowski','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('509','ikrawc','Ireneusz','Krawczak','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('510','nchmie','Norbert','Chmiel ','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('511','akozło','Agnieszka','Kozłowska','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('512','ssobol','Sylwia','Sobolewska','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('513','rświde','Ryszard','Świderski ','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('514','jkrzes','Jarosław','Krzesiński','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('515','gmarci','Gabriela','Marciniak','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('516','polsze','Paweł','Olszewski','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('517','kmakow','Kazimierz','Makowski','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('518','jwesoł','Justyna','Wesołowska','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('519','hjanik','Henryk','Janik','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('520','akrzes','Andrzej','Krzesiński','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('521','jkrupa','Julia','Krupa','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('522','ljasiń','Leszek','Jasiński','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('523','ezawad','Emilia','Zawadzka','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('524','itomcz','Igor','Tomczak','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('525','iczerw','Iwona','Czerwińska','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('526','kwojci','Karolina','Wojciechowska','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('527','pdudek','Patrycja','Dudek','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('528','apasie','Anna Maria','Pasieka','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('529','rbaran','Ryszard','Baranowski','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('530','jłucza','Julia','Łuczak','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('531','mkubic','Marzena','Kubicka','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('532','isosno','Ireneusz','Sosnowski','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('533','dgłowa','Damian','Głowacki','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('534','jbrzez','Jacek','Brzeziński','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('535','jmalin','Janusz','Malinowski','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('536','wpawli','Waldemar','Pawlik','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('537','izawad','Izabela','Zawadzka','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('538','kwesoł','Katarzyna','Wesołowska','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('539','dmrozo','Dariusz','Mrozowski ','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('540','kgórsk','Kamila','Górska','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('541','kczajk','Kinga','Czajkowska','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('542','ssikor','Sylwia','Sikora','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('543','mmikoł','Marzena','Mikołajczyk','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('544','mmadej','Marzena','Madej','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('545','atomcz','Adam','Tomczak','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('546','zskiba','Zbigniew','Skiba','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('547','mskals','Mariusz','Skalski','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('548','jurbań','Jarosław','Urbański','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('549','awłoda','Anna Maria','Włodarczyk ','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('550','uwilk','Urszula','Wilk','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('551','epiotr','Ewelina','Piotrowska','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('552','akwiat','Agnieszka','Kwiatkowska','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('553','pkozak','Paulina','Kozak','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('554','awalcz','Anita','Walczak','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('555','abedna','Aleksandra','Bednarska','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('556','jzakrz','Jakub','Zakrzewski','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('557','jwiśni','Janusz','Wiśniewski','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('558','jzawad','Julia','Zawadzka','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('559','mkołod','Mirosław','Kołodziej','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('560','mduda','Monika','Duda','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('561','mskowr','Marek','Skowroński','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('562','jkubia','Jarosław','Kubiak','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('563','jsawic','Justyna','Sawicka','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('564','hcieśl','Henryk','Cieślak','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('565','ekozak','Elżbieta','Kozak','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('566','dstępi','Daniel','Stępień','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('567','aczarn','Aleksandra','Czarnecka','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('568','jwesoł','Janusz','Wesołowski','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('569','krogow','Kacper','Rogowski','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('570','anowak','Agata','Nowak','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('571','dgrzyb','Dominika','Grzybowska','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('572','mrogow','Mirosław','Rogowski','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('573','dszymc','Daniel','Szymczak ','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('574','mmalin','Mariusz','Malinowski','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('575','mwróbe','Maria','Wróbel','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('576','pmróz','Paweł','Mróz','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('577','akaczm','Aleksandra','Kaczmarczyk','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('578','mkról','Małgorzata','Król','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('579','amikoł','Agnieszka','Mikołajczyk','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('580','ajanko','Anna Maria','Jankowska','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('581','tpolak','Tadeusz','Polak','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('582','aborow','Alicja','Borowska ','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('583','dzawad','Dorota','Zawadzka','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('584','iwitko','Irena','Witkowska','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('585','łkwiat','Łukasz','Kwiatkowski','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('586','zgórsk','Zbigniew','Górski','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('587','kmalin','Katarzyna','Malinowska','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('588','mkrawc','Małgorzata','Krawczyk','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('589','ipiąte','Igor','Piątek','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('590','jzając','Joanna','Zając','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('591','jkubic','Jan','Kubicki','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('592','aolsze','Alicja','Olszewska','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('593','mzając','Monika','Zając','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('594','mczarn','Mirosław','Czarnecki','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('595','jkrzes','Jakub','Krzesiński','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('596','ilewan','Ireneusz','Lewandowski','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('597','wżukow','Waldemar','Żukowski','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('598','mczarn','Marcin','Czarnecki','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('599','gkrzes','Grzegorz','Krzesiński','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('600','bgłowa','Beata','Głowacka','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('601','kkraje','Klaudia','Krajewska ','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('602','molsze','Monika','Olszewska','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('603','kłukas','Katarzyna','Łukasik','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('604','mcieśl','Michał','Cieślik ','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('605','aszulc','Adam','Szulc','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('606','apasze','Andrzej','Paszek','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('607','iadamc','Irena','Adamczyk','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('608','mbaran','Marek','Baranowski','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('609','mmicha','Marek','Michalski','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('610','atomas','Agata','Tomaszewska','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('611','skania','Sebastian','Kania','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('612','jwrona','Jan','Wrona ','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('613','mświde','Marek','Świderski ','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('614','akrupa','Anna','Krupa','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('615','csikor','Cezary','Sikorski','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('616','wkwiat','Waldemar','Kwiatkowski','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('617','msobol','Magdalena','Sobolewska','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('618','wmarci','Wioletta','Marciniak','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('619','jpasze','Janusz','Paszek','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('620','rleśni','Radosław','Leśniak','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('621','ksobol','Klaudia','Sobolewska','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('623','dolsze','Dariusz','Olszewski','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('643','tnowic','Teresa','Nowicka','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('662','jszewc','Justyna','Szewczyk','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('682','ałucza','Agata','Łuczak','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('702','dleśni','Damian','Leśniak','4');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('745','pmakow','Patrycja','Makowska','7');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('746','ujasiń','Urszula','Jasińska','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('747','jborko','Jakub','Borkowski ','6');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('748','ksobcz','Kinga','Sobczak','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('749','rjóźwi','Robert','Jóźwiak ','2');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('750','jrogow','Jan','Rogowski','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('782','rcieśl','Radosław','Cieślak','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('784','ltarno','Leszek','Tarnowski','1');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('785','pwojci','Paulina','Wojciechowska','3');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('803','jbedna','Janusz','Bednarski','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('822','jtomcz','Jarosław','Tomczak','8');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('847','eszyma','Ewa','Szymańska','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('846','bmikoł','Bartłomiej','Mikołajczak','9');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('848','iwiśni','Irena','Wiśniewska','10');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('849','kmalin','Klaudia','Malinowska','5');
Insert into EXAMPLE_USERS (ID,LOGIN,IMIE,NAZWISKO,DEPARTMENT_ID) values ('850','swilk','Sylwia','Wilk','9');
--------------------------------------------------------
--  Constraints for Table EXAMPLE_USERS
--------------------------------------------------------

  ALTER TABLE "EXAMPLE_USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EXAMPLE_USERS
--------------------------------------------------------

  ALTER TABLE "EXAMPLE_USERS" ADD CONSTRAINT "FK_USERS_EXAMPLE_DEPT" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "EXAMPLE_DEPARTMENTS" ("ID") ENABLE;
